# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI2
env: SCREENER_API_KEY:${{secrects.SCREENER_API_KEY}}
  SAUCE_USERNAME:${{secrects.SCREENER_USERNAME}}
  SAUCE_ACCESS_KEY:${{secrects.ACCESS_API_KEY}}
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          cd reactapptest
          npm ci
      - run: npm run build --if-present
      - name: Run component tests
        run: |
          cd reactapptest
          npm run test
      - name: Start the app
        run: |
          cd reactapptest
          npm start &
          npm wait-on-- timeout 60000
